# Generated by Django 5.2 on 2025-04-09 03:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_alter_subject_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommendation_type', models.CharField(choices=[('lesson', 'Bài học'), ('quiz', 'Bài kiểm tra'), ('flashcard', 'Flashcard'), ('exercise', 'Bài tập thực hành'), ('project', 'Dự án học tập')], max_length=20)),
                ('external_content_url', models.URLField(blank=True, null=True)),
                ('relevance_score', models.FloatField(default=0.0, help_text='Điểm liên quan từ 0.0 đến 1.0')),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_helpful', models.BooleanField(blank=True, help_text='Người dùng đánh giá đề xuất có hữu ích không', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='content.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='content.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-relevance_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Người mới bắt đầu'), ('intermediate', 'Trung cấp'), ('advanced', 'Nâng cao'), ('expert', 'Chuyên gia')], default='beginner', max_length=20)),
                ('estimated_duration_days', models.PositiveIntegerField(default=30, help_text='Thời gian ước tính để hoàn thành (ngày)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_pathways', to='content.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_pathways', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_learning_style', models.CharField(choices=[('visual', 'Học bằng hình ảnh'), ('auditory', 'Học bằng âm thanh'), ('reading', 'Học bằng đọc'), ('kinesthetic', 'Học bằng thực hành')], default='visual', max_length=20)),
                ('preferred_difficulty', models.CharField(choices=[('easy_to_hard', 'Từ dễ đến khó'), ('hard_to_easy', 'Từ khó đến dễ'), ('mixed', 'Kết hợp')], default='easy_to_hard', max_length=20)),
                ('preferred_study_time', models.TimeField(default=django.utils.timezone.now, help_text='Thời gian học tập ưa thích')),
                ('preferred_session_duration', models.PositiveIntegerField(default=30, help_text='Thời lượng phiên học ưa thích (phút)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_topics', models.ManyToManyField(blank=True, related_name='interested_users', to='content.topic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PathwayStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('step_type', models.CharField(choices=[('lesson', 'Bài học'), ('quiz', 'Bài kiểm tra'), ('exercise', 'Bài tập thực hành'), ('project', 'Dự án nhỏ'), ('assessment', 'Đánh giá')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự của bước trong lộ trình')),
                ('external_content_url', models.URLField(blank=True, help_text='URL đến nội dung bên ngoài nếu có', null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=30, help_text='Thời gian ước tính để hoàn thành (phút)')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathway_steps', to='content.lesson')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_steps', to='personalization.learningpathway')),
            ],
            options={
                'ordering': ['pathway', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudyReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('reminder_type', models.CharField(choices=[('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('custom', 'Tùy chỉnh')], default='daily', max_length=20)),
                ('notification_method', models.CharField(choices=[('app', 'Thông báo trong ứng dụng'), ('email', 'Email'), ('both', 'Cả hai')], default='app', max_length=20)),
                ('reminder_time', models.TimeField(default=django.utils.timezone.now)),
                ('days_of_week', models.CharField(blank=True, help_text='Các ngày trong tuần, định dạng: 0,1,2,3,4,5,6 (0=Thứ Hai)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UIPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_theme', models.CharField(choices=[('light', 'Sáng'), ('dark', 'Tối'), ('blue', 'Xanh dương'), ('green', 'Xanh lá'), ('purple', 'Tím'), ('orange', 'Cam')], default='light', max_length=20)),
                ('font_size', models.CharField(choices=[('small', 'Nhỏ'), ('medium', 'Vừa'), ('large', 'Lớn'), ('x-large', 'Rất lớn')], default='medium', max_length=20)),
                ('enable_animations', models.BooleanField(default=True)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Xem'), ('complete', 'Hoàn thành'), ('like', 'Thích'), ('bookmark', 'Đánh dấu'), ('share', 'Chia sẻ'), ('rate', 'Đánh giá')], max_length=20)),
                ('content_type', models.CharField(choices=[('lesson', 'Bài học'), ('quiz', 'Bài kiểm tra'), ('flashcard', 'Flashcard'), ('exercise', 'Bài tập thực hành'), ('project', 'Dự án học tập'), ('pathway', 'Lộ trình học tập')], max_length=20)),
                ('content_id', models.PositiveIntegerField(help_text='ID của nội dung tương tác')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Đánh giá từ 1-5 sao', null=True)),
                ('interaction_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-interaction_time'],
                'indexes': [models.Index(fields=['user', 'content_type', 'content_id'], name='personaliza_user_id_98553b_idx'), models.Index(fields=['content_type', 'content_id'], name='personaliza_content_3ef336_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserStrengthWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_strength', models.BooleanField(default=True, help_text='True nếu là điểm mạnh, False nếu là điểm yếu')),
                ('proficiency_score', models.FloatField(default=0.0, help_text='Điểm thành thạo từ 0.0 đến 1.0')),
                ('last_assessment_date', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú về điểm mạnh/yếu')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assessments', to='content.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assessments', to='content.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strengths_weaknesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-proficiency_score'],
                'unique_together': {('user', 'subject', 'topic')},
            },
        ),
    ]
