# Generated by Django 5.2 on 2025-04-08 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_learning', '0002_userproject_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Thông tin'), ('success', 'Thành công'), ('warning', 'Cảnh báo'), ('danger', 'Quan trọng')], default='info', max_length=20)),
                ('related_feature', models.CharField(choices=[('pomodoro', 'Pomodoro Timer'), ('cornell', 'Cornell Notes'), ('mindmap', 'Mind Mapping'), ('feynman', 'Feynman Technique'), ('project', 'Project-Based Learning'), ('exercise', 'Interactive Exercises'), ('competition', 'Competition Mode'), ('system', 'Hệ thống')], default='system', max_length=20)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
