# Generated by Django 5.2 on 2025-04-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advanced_learning", "0004_alter_notification_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cornellnote",
            name="is_shared",
            field=models.BooleanField(
                default=False, help_text="Ghi chú có được chia sẻ không"
            ),
        ),
        migrations.AddField(
            model_name="cornellnote",
            name="last_review_date",
            field=models.DateTimeField(
                blank=True, help_text="Ngày ôn tập gần nhất", null=True
            ),
        ),
        migrations.AddField(
            model_name="cornellnote",
            name="next_review_date",
            field=models.DateTimeField(
                blank=True, help_text="Ngày ôn tập tiếp theo", null=True
            ),
        ),
        migrations.AddField(
            model_name="cornellnote",
            name="review_count",
            field=models.PositiveIntegerField(default=0, help_text="Số lần đã ôn tập"),
        ),
        migrations.AddField(
            model_name="cornellnote",
            name="share_url",
            field=models.CharField(
                blank=True, help_text="URL chia sẻ ghi chú", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="mindmap",
            name="is_shared",
            field=models.BooleanField(
                default=False, help_text="Sơ đồ tư duy có được chia sẻ không"
            ),
        ),
        migrations.AddField(
            model_name="mindmap",
            name="share_url",
            field=models.CharField(
                blank=True,
                help_text="URL chia sẻ sơ đồ tư duy",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mindmap",
            name="style_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Các tùy chọn tùy biến (kiểu đường, hình dạng nút, v.v.)",
                null=True,
            ),
        ),
    ]
