# Generated by Django 5.2 on 2025-04-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "advanced_learning",
            "0005_cornellnote_is_shared_cornellnote_last_review_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="feynmannote",
            name="is_shared",
            field=models.BooleanField(
                default=False, help_text="Ghi chú có được chia sẻ không"
            ),
        ),
        migrations.AddField(
            model_name="feynmannote",
            name="last_review_date",
            field=models.DateTimeField(
                blank=True, help_text="Ngày ôn tập gần nhất", null=True
            ),
        ),
        migrations.AddField(
            model_name="feynmannote",
            name="next_review_date",
            field=models.DateTimeField(
                blank=True, help_text="Ngày ôn tập tiếp theo", null=True
            ),
        ),
        migrations.AddField(
            model_name="feynmannote",
            name="review_count",
            field=models.PositiveIntegerField(default=0, help_text="Số lần đã ôn tập"),
        ),
        migrations.AddField(
            model_name="feynmannote",
            name="share_url",
            field=models.CharField(
                blank=True, help_text="URL chia sẻ ghi chú", max_length=100, null=True
            ),
        ),
    ]
