# Generated by Django 5.2 on 2025-04-08 16:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "advanced_learning",
            "0006_feynmannote_is_shared_feynmannote_last_review_date_and_more",
        ),
        ("flashcards", "0001_initial"),
        ("quizzes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userproject",
            name="feedback",
            field=models.TextField(
                blank=True, help_text="Nhận xét về dự án", null=True
            ),
        ),
        migrations.AddField(
            model_name="userproject",
            name="flashcard_sets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Các bộ flashcard liên quan đến dự án",
                related_name="user_projects",
                to="flashcards.flashcardset",
            ),
        ),
        migrations.AddField(
            model_name="userproject",
            name="is_shared",
            field=models.BooleanField(
                default=False, help_text="Dự án có được chia sẻ không"
            ),
        ),
        migrations.AddField(
            model_name="userproject",
            name="pomodoro_sessions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Các phiên Pomodoro liên quan đến dự án",
                related_name="user_projects",
                to="advanced_learning.pomodorosession",
            ),
        ),
        migrations.AddField(
            model_name="userproject",
            name="quizzes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Các quiz liên quan đến dự án",
                related_name="user_projects",
                to="quizzes.quiz",
            ),
        ),
        migrations.AddField(
            model_name="userproject",
            name="rating",
            field=models.PositiveIntegerField(
                default=0, help_text="Đánh giá dự án (0-5 sao)"
            ),
        ),
        migrations.AddField(
            model_name="userproject",
            name="result_files",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Danh sách các file kết quả dự án",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userproject",
            name="share_url",
            field=models.CharField(
                blank=True, help_text="URL chia sẻ dự án", max_length=100, null=True
            ),
        ),
        migrations.CreateModel(
            name="ProjectComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Nội dung bình luận")),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Đánh giá (0-5 sao)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="advanced_learning.userproject",
                    ),
                ),
            ],
        ),
    ]
