# Generated by Django 5.2 on 2025-04-08 10:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_alter_subject_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('goal_type', models.CharField(choices=[('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('monthly', 'Hàng tháng')], default='weekly', max_length=20, verbose_name='Loại mục tiêu')),
                ('category', models.CharField(choices=[('study_time', 'Thời gian học tập'), ('lessons_completed', 'Số bài học hoàn thành'), ('flashcards_reviewed', 'Số flashcard ôn tập'), ('quizzes_completed', 'Số bài kiểm tra hoàn thành'), ('projects_completed', 'Số dự án hoàn thành'), ('custom', 'Tùy chỉnh')], default='study_time', max_length=20, verbose_name='Danh mục')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('target_value', models.PositiveIntegerField(default=1, verbose_name='Giá trị mục tiêu')),
                ('current_value', models.PositiveIntegerField(default=0, verbose_name='Giá trị hiện tại')),
                ('progress_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Phần trăm tiến độ')),
                ('status', models.CharField(choices=[('not_started', 'Chưa bắt đầu'), ('in_progress', 'Đang thực hiện'), ('completed', 'Đã hoàn thành'), ('overdue', 'Quá hạn')], default='not_started', max_length=20, verbose_name='Trạng thái')),
                ('reminder_enabled', models.BooleanField(default=True, verbose_name='Bật nhắc nhở')),
                ('reminder_frequency', models.CharField(choices=[('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần')], default='daily', max_length=20, verbose_name='Tần suất nhắc nhở')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='content.lesson', verbose_name='Bài học')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='content.subject', verbose_name='Chủ đề')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='content.topic', verbose_name='Chủ đề con')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mục tiêu học tập',
                'verbose_name_plural': 'Mục tiêu học tập',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Giá trị')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learning_goals.learninggoal')),
            ],
            options={
                'verbose_name': 'Tiến độ mục tiêu',
                'verbose_name_plural': 'Tiến độ mục tiêu',
                'ordering': ['-date'],
                'unique_together': {('goal', 'date')},
            },
        ),
    ]
