# Generated by Django 5.2 on 2025-04-08 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggoal',
            name='allow_collaboration',
            field=models.BooleanField(default=False, verbose_name='Cho phép cộng tác'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='badge_description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả huy hiệu'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='badge_level',
            field=models.CharField(choices=[('bronze', 'Đồng'), ('silver', 'Bạc'), ('gold', 'Vàng'), ('platinum', 'Bạch kim')], default='bronze', max_length=20, verbose_name='Cấp độ huy hiệu'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='badge_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên huy hiệu'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='has_badge_reward',
            field=models.BooleanField(default=False, verbose_name='Có huy hiệu thưởng'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Công khai'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='reward_points',
            field=models.PositiveIntegerField(default=10, verbose_name='Điểm thưởng'),
        ),
        migrations.CreateModel(
            name='GoalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='learning_goals.learninggoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Người xem'), ('collaborator', 'Người cộng tác'), ('admin', 'Quản trị viên')], default='viewer', max_length=20, verbose_name='Vai trò')),
                ('message', models.TextField(blank=True, verbose_name='Lời nhắn')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('accepted', 'Đã chấp nhận'), ('declined', 'Đã từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='learning_goals.learninggoal')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lời mời',
                'verbose_name_plural': 'Lời mời',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Người xem'), ('collaborator', 'Người cộng tác'), ('admin', 'Quản trị viên')], default='viewer', max_length=20, verbose_name='Vai trò')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='learning_goals.learninggoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborated_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Người cộng tác',
                'verbose_name_plural': 'Người cộng tác',
                'unique_together': {('goal', 'user')},
            },
        ),
    ]
