# Generated by Django 5.2 on 2025-04-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_goals', '0002_learninggoal_allow_collaboration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggoal',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Lặp lại mục tiêu'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='recurring_frequency',
            field=models.CharField(choices=[('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('monthly', 'Hàng tháng'), ('custom', 'Tùy chỉnh')], default='weekly', max_length=20, verbose_name='Tần suất lặp lại'),
        ),
    ]
