# Generated by Django 5.2 on 2025-04-10 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_alter_subject_icon'),
        ('flashcards', '0002_alter_flashcard_options_flashcard_is_auto_generated_and_more'),
        ('quizzes', '0002_question_is_auto_generated_quiz_is_auto_generated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_study_time', models.BooleanField(default=True, help_text='Hiển thị thời gian học tập')),
                ('show_quiz_performance', models.BooleanField(default=True, help_text='Hiển thị hiệu suất làm bài kiểm tra')),
                ('show_flashcard_performance', models.BooleanField(default=True, help_text='Hiển thị hiệu suất học flashcard')),
                ('show_subject_distribution', models.BooleanField(default=True, help_text='Hiển thị phân bố thời gian theo chủ đề')),
                ('show_learning_patterns', models.BooleanField(default=True, help_text='Hiển thị mẫu học tập')),
                ('show_recommendations', models.BooleanField(default=True, help_text='Hiển thị đề xuất học tập')),
                ('dashboard_refresh_rate', models.IntegerField(default=24, help_text='Tần suất làm mới bảng điều khiển (giờ)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('monthly', 'Hàng tháng'), ('custom', 'Tùy chỉnh')], max_length=10)),
                ('report_format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], default='html', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('report_data', models.JSONField(default=dict)),
                ('is_generated', models.BooleanField(default=False)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('strength', 'Điểm mạnh'), ('weakness', 'Điểm yếu'), ('pattern', 'Mẫu học tập'), ('improvement', 'Cải thiện'), ('milestone', 'Cột mốc'), ('custom', 'Tùy chỉnh')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data_points', models.JSONField(default=dict, help_text='Dữ liệu hỗ trợ cho phân tích')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Nổi bật trên bảng điều khiển')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_insights', to='content.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_insights', to='content.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('study_time', 'Thời gian học tập'), ('quiz_score', 'Điểm bài kiểm tra'), ('flashcard_retention', 'Tỷ lệ ghi nhớ flashcard'), ('completion_rate', 'Tỷ lệ hoàn thành'), ('focus_score', 'Điểm tập trung'), ('consistency_score', 'Điểm độ đều'), ('custom', 'Tùy chỉnh')], max_length=20)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='content.lesson')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='content.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='content.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'metric_type'],
            },
        ),
        migrations.CreateModel(
            name='LearningRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('subject', 'Chủ đề'), ('topic', 'Chủ đề con'), ('lesson', 'Bài học'), ('quiz', 'Bài kiểm tra'), ('flashcard', 'Flashcard'), ('study_habit', 'Thói quen học tập'), ('custom', 'Tùy chỉnh')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao')], default='medium', max_length=10)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('flashcard_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='flashcards.flashcardset')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_recommendations', to='content.lesson')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='quizzes.quiz')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_recommendations', to='content.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_recommendations', to='content.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
