# Generated by Django 5.2 on 2025-04-09 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='flashcard',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='Đánh dấu flashcard được tạo tự động'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị flashcard'),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='Đánh dấu bộ flashcard được tạo tự động'),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
