# Generated by Django 5.2 on 2025-04-09 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='Đánh dấu câu hỏi được tạo tự động'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='Đánh dấu bài kiểm tra được tạo tự động'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Chọn một đáp án'), ('multiple', 'Chọn nhiều đáp án'), ('text', 'Trả lời văn bản'), ('true_false', 'Đúng/Sai')], default='single', max_length=10),
        ),
    ]
