# Generated by Django 5.2 on 2025-04-08 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Thông tin'), ('success', 'Thành công'), ('warning', 'Cảnh báo'), ('danger', 'Quan trọng')], default='info', max_length=20)),
                ('related_feature', models.CharField(choices=[('pomodoro', 'Pomodoro Timer'), ('cornell', 'Cornell Notes'), ('mindmap', 'Mind Mapping'), ('feynman', 'Feynman Technique'), ('project', 'Project-Based Learning'), ('exercise', 'Interactive Exercises'), ('competition', 'Competition Mode'), ('system', 'Hệ thống')], default='system', max_length=20)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_realtime_notifications', models.BooleanField(default=True, help_text='Nhận thông báo thời gian thực trong ứng dụng')),
                ('receive_email_notifications', models.BooleanField(default=True, help_text='Nhận thông báo qua email')),
                ('email_pomodoro', models.BooleanField(default=False, help_text='Nhận email về Pomodoro Timer')),
                ('email_cornell', models.BooleanField(default=False, help_text='Nhận email về Cornell Notes')),
                ('email_mindmap', models.BooleanField(default=False, help_text='Nhận email về Mind Mapping')),
                ('email_feynman', models.BooleanField(default=False, help_text='Nhận email về Feynman Technique')),
                ('email_project', models.BooleanField(default=True, help_text='Nhận email về Project-Based Learning')),
                ('email_exercise', models.BooleanField(default=False, help_text='Nhận email về Interactive Exercises')),
                ('email_competition', models.BooleanField(default=True, help_text='Nhận email về Competition Mode')),
                ('email_system', models.BooleanField(default=True, help_text='Nhận email về hệ thống')),
                ('email_frequency', models.CharField(choices=[('immediately', 'Ngay lập tức'), ('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần')], default='immediately', help_text='Tần suất nhận email thông báo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
